### ISSUE TITLE
TLS o matic serves the homepage in plain-text

### ISSUE THREAD

**Issue by Spindel** [edvinanet/tls-o-matic#1]
Installing the tls-o-matic root ca requires you to trust plaintext HTTP.

I'm connected to a wifi named "(); :(){:|:};:"   And I'm not sure I trust it.

I want to try the TLS O matic tests with my web browser.

There is no safe way for me to do that.

**Comment by oej** [comment]
You can download the cert from Github, but I get your point.

**Comment by oej** [comment]
Certificate installed. Everything seems to run over HTTPS now.

Closing this bug report.
