### ISSUE TITLE
tls o matic test 15 online has wrong cert

### ISSUE THREAD

**Issue by Spindel** [edvinanet/tls-o-matic#3]
## [spider@tear tmp]$ openssl s_client -connect  test15a.tls-o-matic.com:415   -tls1_2

Certificate chain
 0 s:/O=TLS Hosting Company/CN=test15.tls-o-matic.com
   i:/O=Intermediate 1 tls-o-matic.com/CN=TLS-o-matic-intermediate-1
 1 s:/O=TLS-O-Matic Intermediate CA 1/CN=TLS-o-matic-intermediate-1
##    i:/O=D&O TLS-O-MATIC CERTIFICATE AUTHORITY AB/CN=tls-o-matic.com

Server certificate
-----BEGIN CERTIFICATE-----
MIIDyjCCArKgAwIBAgICECMwDQYJKoZIhvcNAQELBQAwTjEnMCUGA1UECgweSW50
ZXJtZWRpYXRlIDEgdGxzLW8tbWF0aWMuY29tMSMwIQYDVQQDDBpUTFMtby1tYXRp
Yy1pbnRlcm1lZGlhdGUtMTAeFw0xNTAzMDIwNjQyNDNaFw0xNjAzMDEwNjQyNDNa
MD8xHDAaBgNVBAoME1RMUyBIb3N0aW5nIENvbXBhbnkxHzAdBgNVBAMMFnRlc3Qx
NS50bHMtby1tYXRpYy5jb20wggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIB
AQC9kuOwUn9OuL+85iHfy5vARUuJxL/5nL3svIZ2WXFrJqCkUVOpCOI0K8s8Ja6p
jhLqeQFVVBHDT87xr+pR3KvQTZvONKoGDY45gc9ErAzK9fi7LAselGVvpJpjF6jD
qvTKolk3/YNK44hR1+oo8UJDf2sJ2RYvL/wWxCDLV/4FXvCngY+4atuoh6FOZqMA
Gs3/JTDkgEmBo2wh9iSWE8rubiPXRdm8kCUeOiaRxRvpjcf0+H+5ZqWIXyJo1jum
+755+O0Mc/YLGRkS+qU/1HB98iU08bWHdY9XPpcj5dQqE9t+7JL/tLNDbakt8168
8R7eB452Hr5MpnidIndHfVRjAgMBAAGjgcAwgb0wCQYDVR0TBAIwADATBgNVHSUE
DDAKBggrBgEFBQcDATA6BglghkgBhvhCAQ0ELRYrVExTLU8tTWF0aWMgTm8gVmFs
aWRhdGlvbiBDZXJ0aWZpY2F0ZSDwn5KwIDAdBgNVHQ4EFgQUEg07frLNP/Bnh4ai
XL+j2gGz01wwHwYDVR0jBBgwFoAUj2sf5501XDzU6ht5pYOt/peai9EwHwYDVR0R
BBgwFoEUaW5mb0B0bHMtby1tYXRpYy5jb20wDQYJKoZIhvcNAQELBQADggEBAMeR
YsNRFBVtuQLMJCe2EUDy3BYUKS2tBGGwoeffRLg4u2dWtWsIToLe3toj2prJVOHa
sBi/7STQrdwmlRqXadmgsSoxixQ0GXyZE7LFT1XOZY3X8sNPYOOwAUgqZZVC7cki
HKm4rb0bKJLUF9ZEg2m8F8hzBjurPFqdTiWvJXNfJaA4pNYPuRl1msZJ4F7depWl
P3MsL3OEqbP9w/pvfHukukrWJtPbjkVNtR2PJGmDKbvnScH63gUcfxRVdQYLRabH
2CDmq/ULFCHAmqSVESI7OlmqEOfX5MkVqTwdHHcP/jYFyt7N1t7RdC1lewlwWdbJ
fNoWM9lK7Ce5frWtCVs=
-----END CERTIFICATE-----
## [spider@tear tmp]$ openssl s_client -connect  test15b.tls-o-matic.com:415   -tls1_2

Certificate chain
 0 s:/O=TLS Hosting Company/CN=test15.tls-o-matic.com
   i:/O=Intermediate 1 tls-o-matic.com/CN=TLS-o-matic-intermediate-1
 1 s:/O=TLS-O-Matic Intermediate CA 1/CN=TLS-o-matic-intermediate-1
##    i:/O=D&O TLS-O-MATIC CERTIFICATE AUTHORITY AB/CN=tls-o-matic.com

Server certificate
-----BEGIN CERTIFICATE-----
MIIDyjCCArKgAwIBAgICECMwDQYJKoZIhvcNAQELBQAwTjEnMCUGA1UECgweSW50
ZXJtZWRpYXRlIDEgdGxzLW8tbWF0aWMuY29tMSMwIQYDVQQDDBpUTFMtby1tYXRp
Yy1pbnRlcm1lZGlhdGUtMTAeFw0xNTAzMDIwNjQyNDNaFw0xNjAzMDEwNjQyNDNa
MD8xHDAaBgNVBAoME1RMUyBIb3N0aW5nIENvbXBhbnkxHzAdBgNVBAMMFnRlc3Qx
NS50bHMtby1tYXRpYy5jb20wggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIB
AQC9kuOwUn9OuL+85iHfy5vARUuJxL/5nL3svIZ2WXFrJqCkUVOpCOI0K8s8Ja6p
jhLqeQFVVBHDT87xr+pR3KvQTZvONKoGDY45gc9ErAzK9fi7LAselGVvpJpjF6jD
qvTKolk3/YNK44hR1+oo8UJDf2sJ2RYvL/wWxCDLV/4FXvCngY+4atuoh6FOZqMA
Gs3/JTDkgEmBo2wh9iSWE8rubiPXRdm8kCUeOiaRxRvpjcf0+H+5ZqWIXyJo1jum
+755+O0Mc/YLGRkS+qU/1HB98iU08bWHdY9XPpcj5dQqE9t+7JL/tLNDbakt8168
8R7eB452Hr5MpnidIndHfVRjAgMBAAGjgcAwgb0wCQYDVR0TBAIwADATBgNVHSUE
DDAKBggrBgEFBQcDATA6BglghkgBhvhCAQ0ELRYrVExTLU8tTWF0aWMgTm8gVmFs
aWRhdGlvbiBDZXJ0aWZpY2F0ZSDwn5KwIDAdBgNVHQ4EFgQUEg07frLNP/Bnh4ai
XL+j2gGz01wwHwYDVR0jBBgwFoAUj2sf5501XDzU6ht5pYOt/peai9EwHwYDVR0R
BBgwFoEUaW5mb0B0bHMtby1tYXRpYy5jb20wDQYJKoZIhvcNAQELBQADggEBAMeR
YsNRFBVtuQLMJCe2EUDy3BYUKS2tBGGwoeffRLg4u2dWtWsIToLe3toj2prJVOHa
sBi/7STQrdwmlRqXadmgsSoxixQ0GXyZE7LFT1XOZY3X8sNPYOOwAUgqZZVC7cki
HKm4rb0bKJLUF9ZEg2m8F8hzBjurPFqdTiWvJXNfJaA4pNYPuRl1msZJ4F7depWl
P3MsL3OEqbP9w/pvfHukukrWJtPbjkVNtR2PJGmDKbvnScH63gUcfxRVdQYLRabH
2CDmq/ULFCHAmqSVESI7OlmqEOfX5MkVqTwdHHcP/jYFyt7N1t7RdC1lewlwWdbJ
fNoWM9lK7Ce5frWtCVs=
-----END CERTIFICATE-----
subject=/O=TLS Hosting Company/CN=test15.tls-o-matic.com
## issuer=/O=Intermediate 1 tls-o-matic.com/CN=TLS-o-matic-intermediate-1

No client certificate CA names sent

This certificate DOESNT have SNI host extensions

Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number: 4131 (0x1023)
    Signature Algorithm: sha256WithRSAEncryption
        Issuer: O=Intermediate 1 tls-o-matic.com, CN=TLS-o-matic-intermediate-1
        Validity
            Not Before: Mar  2 06:42:43 2015 GMT
            Not After : Mar  1 06:42:43 2016 GMT
        Subject: O=TLS Hosting Company, CN=test15.tls-o-matic.com
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                Public-Key: (2048 bit)
                Modulus:
                    00:bd:92:e3:b0:52:7f:4e:b8:bf:bc:e6:21:df:cb:
                    9b:c0:45:4b:89:c4:bf:f9:9c:bd:ec:bc:86:76:59:
                    71:6b:26:a0:a4:51:53:a9:08:e2:34:2b:cb:3c:25:
                    ae:a9:8e:12:ea:79:01:55:54:11:c3:4f:ce:f1:af:
                    ea:51:dc:ab:d0:4d:9b:ce:34:aa:06:0d:8e:39:81:
                    cf:44:ac:0c:ca:f5:f8:bb:2c:0b:1e:94:65:6f:a4:
                    9a:63:17:a8:c3:aa:f4:ca:a2:59:37:fd:83:4a:e3:
                    88:51:d7:ea:28:f1:42:43:7f:6b:09:d9:16:2f:2f:
                    fc:16:c4:20:cb:57:fe:05:5e:f0:a7:81:8f:b8:6a:
                    db:a8:87:a1:4e:66:a3:00:1a:cd:ff:25:30:e4:80:
                    49:81:a3:6c:21:f6:24:96:13:ca:ee:6e:23:d7:45:
                    d9:bc:90:25:1e:3a:26:91:c5:1b:e9:8d:c7:f4:f8:
                    7f:b9:66:a5:88:5f:22:68:d6:3b:a6:fb:be:79:f8:
                    ed:0c:73:f6:0b:19:19:12:fa:a5:3f:d4:70:7d:f2:
                    25:34:f1:b5:87:75:8f:57:3e:97:23:e5:d4:2a:13:
                    db:7e:ec:92:ff:b4:b3:43:6d:a9:2d:f3:5e:bc:f1:
                    1e:de:07:8e:76:1e:be:4c:a6:78:9d:22:77:47:7d:
                    54:63
                Exponent: 65537 (0x10001)
        X509v3 extensions:
            X509v3 Basic Constraints: 
                CA:FALSE
            X509v3 Extended Key Usage: 
                TLS Web Server Authentication
            Netscape Comment: 
                TLS-O-Matic No Validation Certificate 💰 
            X509v3 Subject Key Identifier: 
                12:0D:3B:7E:B2:CD:3F:F0:67:87:86:A2:5C:BF:A3:DA:01:B3:D3:5C
            X509v3 Authority Key Identifier: 
                keyid:8F:6B:1F:E7:9D:35:5C:3C:D4:EA:1B:79:A5:83:AD:FE:97:9A:8B:D1

```
        X509v3 Subject Alternative Name: 
            email:info@tls-o-matic.com
Signature Algorithm: sha256WithRSAEncryption
     c7:91:62:c3:51:14:15:6d:b9:02:cc:24:27:b6:11:40:f2:dc:
     16:14:29:2d:ad:04:61:b0:a1:e7:df:44:b8:38:bb:67:56:b5:
     6b:08:4e:82:de:de:da:23:da:9a:c9:54:e1:da:b0:18:bf:ed:
     24:d0:ad:dc:26:95:1a:97:69:d9:a0:b1:2a:31:8b:14:34:19:
     7c:99:13:b2:c5:4f:55:ce:65:8d:d7:f2:c3:4f:60:e3:b0:01:
     48:2a:65:95:42:ed:c9:22:1c:a9:b8:ad:bd:1b:28:92:d4:17:
     d6:44:83:69:bc:17:c8:73:06:3b:ab:3c:5a:9d:4e:25:af:25:
     73:5f:25:a0:38:a4:d6:0f:b9:19:75:9a:c6:49:e0:5e:dd:7a:
     95:a5:3f:73:2c:2f:73:84:a9:b3:fd:c3:fa:6f:7c:7b:a4:ba:
     4a:d6:26:d3:db:8e:45:4d:b5:1d:8f:24:69:83:29:bb:e7:49:
     c1:fa:de:05:1c:7f:14:55:75:06:0b:45:a6:c7:d8:20:e6:ab:
     f5:0b:14:21:c0:9a:a4:95:11:22:3b:3a:59:aa:10:e7:d7:e4:
     c9:15:a9:3c:1d:1c:77:0f:fe:36:05:ca:de:cd:d6:de:d1:74:
     2d:65:7b:09:70:59:d6:c9:7c:da:16:33:d9:4a:ec:27:b9:7e:
     b5:ad:09:5b
```

**Comment by Spindel** [comment]
This may be user error:
`openssl s_client -connect  test15a.tls-o-matic.com:415 -servername test15a.tls-o-matic.com   -tls1_2`  because obviously this causes problems because s_client doesn't speak SNI natively...

**Comment by oej** [comment]
I think it's an error with s_client - just tested again with Safari and I get the right certs.
